name: CI

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  docker-build-publish:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/docker-build-publish.yml@main
    with:
      image-name: "orthanc"
      image-version: "1.0-0.1.0"
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}